### ISSUE TITLE
Feature request: custom characteristics slider for delay

### ISSUE THREAD

**Issue by Nastras** [hans-1/homebridge-cmdtriggerswitch#1]
Hello, cool plugin you made. Thanks!

Would it be possible to add a slider to the delay switch for the delay time and a switch to disable the delay as custom characteristics.

Then you could set the delay time directly in homekit.

![B1BB0967-E1F8-4A54-92F5-D28282CEF56C](https://user-images.githubusercontent.com/27686185/72634006-fc8a0e00-3959-11ea-9413-a1dd1de2a6e3.jpeg)

I use this switch from the homebridge automation switches plugin but it doesn't support cmd. But maybe you can use the code?

https://github.com/grover/homebridge-automation-switches

**Comment by hans-1** [comment]
Looks interesting. I will look into it.

**Comment by Nastras** [comment]
👍👌👍 Thanks!

**Comment by Nastras** [comment]
Hello, I would like to ask what are the chances of you implementing it?

**Comment by hans-1** [comment]
Chances are good, actually I am already working on it. But please keep in mind that I am doing this in my spare time so I cannot give you a timeframe.

**Comment by Nastras** [comment]
That sounds great. I didn't mean to stress you out. I just wanted to know if it was coming because I was waiting so long instead of using a workaround on shortcuts. Thanks!

**Comment by Nastras** [comment]
Hello @hans-1,
unfortunately I only got around to testing the new function in detail today.
I must say that I am absolutely thrilled how you have implemented it. Great job!

Thanks a lot for that!!!

I have an additional suggestion which I will tell you in another issue.
